### PR TITLE
Blog featured

### PR DESCRIPTION
**Pull request by JimWasHere**
## Description ##

Made preview card for featured blog post.

## Screen shots or GIFs of UI changes ##
Screen Shot 2022-06-12 at 4 26 39 PM

## Type of change ##

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [X ] Part of a feature.
- [ ] Refactor (non-breaking change which does not add functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Testing-

## Checklist ##

- [X ] I have performed a self-review of my own code
- [X ] I have commented my code, particularly in hard-to-understand areas
- [X ] My changes generate no new warnings
- [X ] added new dependencies
- [ ] added tests
- [ ] updated documentation
- [X] Looks good on large screens
- [X] Looks good on mobile

## Organization ##

- [ ] Have you linked this pull request to a [project ticket](https://trello.com/b/Sdadc2L9/ud-website-v3)? 

## Review ##

- [ ] Is this a work in progress?
- [X ] Is this ready to be reviewed?
- [X ] Have you added two reviewers to this pull request
featured
?

### CODE REVIEW

**Comment by JimWasHere** [comment]
[Create Most Recent Post Preview](https://trello.com/c/2TcbLe4V/23-create-most-recent-post-preview)

**Comment by DennieCodes** [comment]
[Create View blog entry page with dummy blog info for now and image placeholders or dummy images](https://trello.com/c/RtkJjleR/27-create-view-blog-entry-page-with-dummy-blog-info-for-now-and-image-placeholders-or-dummy-images)

**Comment by UnderdogDevsIntake** [comment]
Please add screenshots of the work done

**Comment by UnderdogDevsIntake** [comment]
The linter check is failing, please look into this issue

**Review by UnderdogDevsIntake — APPROVED** [review]
I added some minor changes to branch and approve for merge

**Pull request merged**
